"""Smoke-test target: human HMG-CoA reductase catalytic domain + rosuvastatin.

Sequence is the exact construct crystallized in PDB 1HWL (catalytic portion of
human HMGCR bound to rosuvastatin, formerly ZD4522), fetched from RCSB:
https://www.rcsb.org/structure/1HWL

Ligand is rosuvastatin (PubChem CID 446157, PDB chemical component FBI),
SMILES fetched from PubChem PUG-REST and cross-checked: RDKit parses it to
formula C22H28FN3O6S, matching rosuvastatin's known molecular formula.
"""

HMGCR_1HWL_SEQUENCE = (
    "GAMASSVLVTQEPEIELPREPRPNEECLQILGNAEKGAKFLSDAEIIQLVNAKHIPAYKLETLIETHERGV"
    "SIRRQLLSKKLSEPSSLQYLPYRDYNYSLVMGACCENVIGYMPIPVGVAGPLCLDEKEFQVPMATTEGCLV"
    "ASTNRGCRAIGLGGGASSRVLADGMTRGPVVRLPRACDSAEVKAWLETSEGFAVIKEAFDSTSRFARLQK"
    "LHTSIAGRNLYIRFQSRSGDAMGMNMISKGTEKALSKLHEYFPEMQILAVSGNYCTDKKPAAINWIEGRG"
    "KSVVCEAVIPAKVVREVLKTTTEAMIEVNINKNLVGSAMAGSIGGYNAHAANIVTAIYIACGQDAAQNVG"
    "SSNCITLMEASGPTNEDLYISCTMPSIEIGTVGGGTNLLPQQACLQMLGVQGACKDNPGENARQLARIVC"
    "GTVMAGELSLMAALAAGHLVKSHMIHNRSKINLQDLQGACTKKTA"
)

ROSUVASTATIN_SMILES = (
    "CC(C)C1=NC(=NC(=C1/C=C/[C@H](C[C@H](CC(=O)O)O)O)C2=CC=C(C=C2)F)N(C)S(=O)(=O)C"
)
